apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  labels: 
    app: nodeapp
spec: 
  selector:
    app: nodeapp
  type: LoadBalancer
  externalIPs: 
  - 172.23.128.1
  ports:
  - protocol: TCP
    name: http
    targetPort: 3000
    port: 80
  