apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  labels: 
    app: nodeapp
spec: 
  selector:
    app: nodeapp
  type: ClusterIP
  #externalIPs:
  #- 172.16.0.53
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 3000
    
  